[package]
name = "code-gen-tests-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
code-gen-core = {path = "../code-gen-core"}

[dev-dependencies]
assert_cmd = "~1.0.5"
