name: CI Build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    # We want to run on external PRs, but not on internal ones as push automatically builds
    # H/T: https://github.com/Dart-Code/Dart-Code/commit/612732d5879730608baa9622bf7f5e5b7b51ae65
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'amzn/ion-cli'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # this is used for code gen test gradle project at `code-gen-projects/java/code-gen-demo`
      - name: Use java 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Make gradlew executable
        if: matrix.os == 'windows-2019'
        run: chmod +x ./code-gen-projects/java/code-gen-demo/gradlew
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --workspace --all-features
      - name: Rustfmt Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose -- --check
