name: Continuous deployment
on:
  push:
    branches: [ wasm-experiment ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Build
        working-directory: ./ion-cli-wasm
        run: |
          trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/wasm-experiment'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ion-cli-wasm/dist
          force_orphan: true